# Generated by Django 3.1.2 on 2020-10-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='maxtime',
            field=models.IntegerField(default=90),
        ),
    ]
