# Generated by Django 3.1.2 on 2021-04-24 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_court_maxtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('play_time', models.IntegerField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.court')),
            ],
        ),
    ]
